[toolchain]
channel = "nightly"
profile = "minimal"
components = [ "rustfmt", "clippy", "rust-analyzer", "rust-src" ]
targets = [
    "wasm32-wasip2", # extensions
    "x86_64-unknown-linux-musl", # remote server
]
